package db

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// EngineKind identifies which on-disk format a java-tron store uses.
// Both engines coexist on a single node — java-tron's
// `storage.db.engine` is global, but for forensic reasons (snapshots
// taken before a config change, mixed-mode test fixtures) dbfork
// detects per-store. In practice all 8 stores share the same engine,
// but we don't ASSUME that.
type EngineKind int

const (
	KindLevelDB EngineKind = iota
	KindRocksDB
)

func (k EngineKind) String() string {
	switch k {
	case KindLevelDB:
		return "leveldb"
	case KindRocksDB:
		return "rocksdb"
	default:
		return "unknown"
	}
}

// DetectKind sniffs `<dataDir>/database/<storeName>/` to decide
// which engine wrote it. Order of evidence, strongest first:
//
//  1. java-tron writes a per-store `engine.properties` file with
//     `ENGINE=LEVELDB` or `ENGINE=ROCKSDB` — the authoritative
//     declaration. Always prefer this when present.
//  2. RocksDB-specific markers (`IDENTITY`, `OPTIONS-NNNNNN`) —
//     LevelDB does not write either.
//  3. Extension heuristic: `.ldb` (Go syndtr/goleveldb convention)
//     or `.sst` (Java iq80/leveldb + RocksDB convention). When only
//     `.sst` is present without RocksDB markers, default to LevelDB
//     because that's what java-tron's snapshot pipeline produces.
//
// Limitations:
//   - A freshly-initialised node before its first compaction has
//     no SST files AND no engine.properties yet. DetectKind errors
//     with a "no engine indicators" message — operators bypass with
//     an explicit `--engine` flag at the CLI.
//   - Mixed `.ldb` + `.sst` without an engine.properties suggests
//     manual intervention or an aborted engine migration;
//     DetectKind refuses to guess.
func DetectKind(dataDir, storeName string) (EngineKind, error) {
	path := filepath.Join(dataDir, "database", storeName)
	dirents, err := os.ReadDir(path)
	if err != nil {
		return 0, fmt.Errorf("dbfork: probe %s: %w", path, err)
	}

	// Step 1: authoritative — java-tron's engine.properties.
	if kind, ok, err := readEngineProperties(filepath.Join(path, "engine.properties")); err != nil {
		return 0, err
	} else if ok {
		return kind, nil
	}

	// Step 2: RocksDB-specific marker files.
	var hasLDB, hasSST, hasRocksMarker bool
	for _, d := range dirents {
		name := d.Name()
		if name == "IDENTITY" || strings.HasPrefix(name, "OPTIONS-") {
			hasRocksMarker = true
			continue
		}
		switch filepath.Ext(name) {
		case ".ldb":
			hasLDB = true
		case ".sst":
			hasSST = true
		}
	}
	if hasRocksMarker {
		return KindRocksDB, nil
	}

	// Step 3: extension heuristic. `.sst` alone is NOT a RocksDB
	// signal — Java iq80/leveldb (what java-tron's snapshot pipeline
	// uses) writes `.sst` too. Without explicit RocksDB markers we
	// default to LevelDB.
	switch {
	case hasLDB || hasSST:
		return KindLevelDB, nil
	default:
		return 0, fmt.Errorf("dbfork: cannot detect engine for %s "+
			"(no engine.properties, no RocksDB markers, no .ldb/.sst "+
			"files); has the node finished initial DB compaction? "+
			"Pass --engine to override", path)
	}
}

// readEngineProperties parses java-tron's per-store engine.properties.
// Returns (kind, true, nil) when the file exists and is parseable;
// (0, false, nil) when the file is missing (signal to fall through to
// other heuristics); (0, false, err) on read failure or unknown value.
//
// Format (per java.util.Properties):
//
//	#Generated by the application.  PLEASE DO NOT EDIT!
//	#Thu Dec 05 12:58:50 CST 2019
//	ENGINE=LEVELDB
//
// We do not invoke a real .properties parser — the file's grammar is
// trivial and a 5-line scan over `key=value` (skipping `#` comments)
// is correct.
func readEngineProperties(path string) (EngineKind, bool, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return 0, false, nil
		}
		return 0, false, fmt.Errorf("dbfork: read %s: %w", path, err)
	}
	for line := range strings.SplitSeq(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if !ok || strings.TrimSpace(k) != "ENGINE" {
			continue
		}
		switch strings.ToUpper(strings.TrimSpace(v)) {
		case "LEVELDB":
			return KindLevelDB, true, nil
		case "ROCKSDB":
			return KindRocksDB, true, nil
		default:
			return 0, false, fmt.Errorf("dbfork: %s: unrecognized ENGINE value %q "+
				"(want LEVELDB or ROCKSDB)", path, v)
		}
	}
	// File exists but has no ENGINE= line — treat as missing.
	return 0, false, nil
}

// Open routes to the right engine implementation given a kind.
// Callers either pass an explicit kind (CLI override) or run
// DetectKind first.
func Open(dataDir, storeName string, kind EngineKind) (Engine, error) {
	switch kind {
	case KindLevelDB:
		return OpenLevelDB(dataDir, storeName)
	case KindRocksDB:
		return OpenRocksDB(dataDir, storeName)
	default:
		return nil, fmt.Errorf("dbfork: unknown engine kind %d", kind)
	}
}
