package dbfork

import (
	"bytes"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/syndtr/goleveldb/leveldb"
	"github.com/syndtr/goleveldb/leveldb/util"
	"google.golang.org/protobuf/encoding/prototext"
	"google.golang.org/protobuf/proto"

	"github.com/tronprotocol/tron-deployment/internal/dbfork/db"
	pb "github.com/tronprotocol/tron-deployment/internal/dbfork/proto/pb"
	"github.com/tronprotocol/tron-deployment/internal/dbfork/stores"
)

// equivalenceEnv is the set of environment variables that gate the
// real Go-vs-Java equivalence run. All three must be set (and resolve
// to existing files) for TestEquivalence_GoVsJava to actually run;
// otherwise the test SKIPs with a clear message so a developer
// without the Java toolkit / Nile fixture can still run `go test ./...`
// without failures.
//
//	DBFORK_NILE_FIXTURE  — path to the unzipped Nile snapshot
//	                       (the parent of `database/`). Generated by
//	                       scripts/build-nile-fixture.sh.
//	DBFORK_JAVA_TOOLKIT  — path to the toolkit.jar that contains the
//	                       java DbFork class. Build via:
//	                       cd tron-docker/tools/toolkit && ./gradlew shadowJar
//	DBFORK_FORK_CONF     — path to the fork.conf to apply. The
//	                       canonical reference is
//	                       tron-docker/tools/toolkit/src/main/resources/fork.conf
//	                       (HOCON). Both tools must see identical
//	                       bytes; the test reads it from this path
//	                       for the Go side and passes it to Java
//	                       unchanged.
const (
	envFixture = "DBFORK_NILE_FIXTURE"
	envJavaJar = "DBFORK_JAVA_TOOLKIT"
	envForkCnf = "DBFORK_FORK_CONF"
)

// TestEquivalence_GoVsJava is the Phase 1 release gate: it proves the
// Go port produces the same on-disk state as java DbFork when both
// are applied to the same Nile snapshot with the same fork.conf.
//
// The test SKIPs unless all three env vars (see equivalenceEnv) are
// set. This makes the local-dev `go test ./...` flow fast (no Nile
// download, no Java toolkit dependency) while still letting CI gate
// releases on the real equivalence proof.
//
// What it does when fully wired:
//
//  1. Copies the Nile fixture to two scratch tempdirs.
//  2. Loads fork.conf via the Go loader; runs MutateApply against
//     copy A.
//  3. Invokes `java -jar <toolkit.jar> db fork -d <copy B> -c <conf>`
//     against copy B.
//  4. For each of the 8 dbfork stores, iterates all key-value pairs
//     in both copies and diffs:
//     - Raw-byte compare for fixed-shape stores (properties,
//     witness_schedule, account-asset, storage-row).
//     - Proto-aware compare for variable-shape stores (witness,
//     account, contract, asset-issue-v2) — handles proto3 map
//     field non-deterministic encoding.
//  5. Reports the first N diffs per store so a failing run is
//     debuggable without t.Fatal'ing on the very first mismatch.
func TestEquivalence_GoVsJava(t *testing.T) {
	fixturePath, ok := mustEnvFile(t, envFixture, "Nile fixture", true)
	if !ok {
		return
	}
	javaJar, ok := mustEnvFile(t, envJavaJar, "java toolkit jar", false)
	if !ok {
		return
	}
	forkConfPath, ok := mustEnvFile(t, envForkCnf, "fork.conf", false)
	if !ok {
		return
	}
	if _, err := exec.LookPath("java"); err != nil {
		t.Skipf("equivalence: java binary not on PATH (set up JDK to run "+
			"the equivalence gate): %v", err)
		return
	}

	// Lay down two independent scratch copies — but ONLY of the 8
	// dbfork stores, not the whole snapshot. A full Nile snapshot is
	// ~90 GB and the giant non-dbfork stores (block, trans,
	// pbft-sign-data, …) blew the GitHub runner's disk when copied
	// twice ("no space left on device"). Both tools touch exactly
	// these 8 stores: Go's Apply opens them on demand and diffStore
	// iterates stores.AllStores; java DbFork's initStore() opens the
	// identical 8 (DbFork.java:120-127) and nothing else. So copying
	// only AllStores is provably sufficient AND cuts each scratch copy
	// from ~90 GB to a few GB.
	scratchGo := t.TempDir()
	scratchJava := t.TempDir()
	t.Logf("equivalence: scratchGo=%s scratchJava=%s", scratchGo, scratchJava)
	for _, dst := range []string{scratchGo, scratchJava} {
		for _, store := range stores.AllStores {
			src := filepath.Join(fixturePath, "database", store)
			if _, statErr := os.Stat(src); statErr != nil {
				// A lite snapshot may legitimately prune a store (e.g.
				// storage-row); skip absent ones rather than fail. The
				// per-store diff will then show 0 keys on both sides.
				t.Logf("equivalence: store %q absent in fixture, skipping copy: %v", store, statErr)
				continue
			}
			if err := copyDir(src, filepath.Join(dst, "database", store)); err != nil {
				t.Fatalf("equivalence: copy store %q to %s: %v", store, dst, err)
			}
		}
	}

	// Apply via Go.
	cfg, err := LoadConfig(forkConfPath)
	if err != nil {
		t.Fatalf("equivalence: load fork.conf: %v", err)
	}
	if _, err := Apply(scratchGo, cfg, Options{}); err != nil {
		t.Fatalf("equivalence: Go Apply: %v", err)
	}

	// Apply via Java DbFork. Output goes to t.Log so a failure has
	// the toolkit's own diagnostic in the test log.
	//
	// --retain-witnesses gating: Java's DbFork.java:160-167 wipes
	// witness + witness_schedule UNCONDITIONALLY when -r is absent,
	// regardless of whether fork.conf has a witnesses section. Go's
	// Apply (apply.go:155) only enters the witness branch when
	// len(cfg.Witnesses) > 0 — a deliberate UX safety call from
	// Task #147 to prevent properties-only fork.confs from
	// silently wiping witnesses. To bridge the divergence here,
	// we mirror Go's gating onto the Java invocation: if the conf
	// lists no witnesses, pass -r so Java also skips the wipe.
	javaArgs := []string{
		// -Xmx4g — Nile lite snapshots are multi-GB; the JDK
		// default heap (~256MB) OOMs the toolkit's account+contract
		// store readers. Configurable via DBFORK_JAVA_HEAP env var.
		javaHeapFlag(),
		"-jar", javaJar, "db", "fork",
		// -d is the output-directory (the PARENT of database/), NOT the
		// database/ dir itself: java DbFork's DbTool.getDB appends
		// `database/<store>` internally (DbFork.java:120 -> DbTool). The
		// Go side mirrors this — Apply(scratchGo) opens
		// scratchGo/database/<store>. Passing scratchJava/database here
		// made java look in scratchJava/database/database/<store> and
		// fail to open the LOCK. (Latent until the gate stopped
		// vacuously skipping — the java path was never exercised.)
		"-d", scratchJava,
		"-c", forkConfPath,
	}
	if len(cfg.Witnesses) == 0 {
		javaArgs = append(javaArgs, "--retain-witnesses")
	}
	javaCmd := exec.Command("java", javaArgs...)
	// Set the working directory to scratchJava so the toolkit's
	// logback writes to scratchJava/logs/ instead of polluting the
	// test runner's CWD.
	javaCmd.Dir = scratchJava
	javaOut, javaErr := javaCmd.CombinedOutput()
	if javaErr != nil {
		t.Fatalf("equivalence: java DbFork: %v\noutput:\n%s", javaErr, javaOut)
	}
	t.Logf("equivalence: java DbFork output:\n%s", javaOut)

	// Normalize physical compaction state before the byte diff. The two
	// tools produce the same LOGICAL state but different PHYSICAL layouts
	// of pre-existing data: Go's Apply opens stores via goleveldb
	// (compaction-on-open, which drops already-deleted DELETE tombstones
	// and resolves multi-version keys to the newest sequence number)
	// while java DbFork (leveldbjni) leaves the store less-compacted and
	// physically retains deleted/obsolete entries. Without normalizing,
	// the diff fails on those tombstoned/overwritten PRE-EXISTING keys —
	// not on any mutation. Forcing a full goleveldb CompactRange on every
	// store on BOTH sides converges them to the canonical live newest-seq
	// / tombstone-free form, so the diff reflects only logical (mutation)
	// differences. Verified on a real Nile snapshot (#168): goleveldb
	// CompactRange of an account-asset store with 51 tombstones converges
	// it to exactly the 27,799-key live set. Real mutation differences
	// survive compaction (it changes physical layout, not logical
	// content), so genuine divergences are still caught.
	normalizeViaCompaction(t, scratchGo)
	normalizeViaCompaction(t, scratchJava)

	// Diff each of the 8 dbfork stores. Order is deterministic
	// (stores.AllStores) so a failing run always reports the same
	// store first, making CI bisection easier.
	for _, store := range stores.AllStores {
		t.Run(store, func(t *testing.T) {
			diffStore(t, store, scratchGo, scratchJava)
		})
	}
}

// normalizeViaCompaction forces a full goleveldb CompactRange of every
// dbfork store under root/database, converging differing physical
// compaction states of the same logical data to the canonical live,
// newest-sequence, tombstone-free form. See the call site + #168.
func normalizeViaCompaction(t *testing.T, root string) {
	t.Helper()
	for _, store := range stores.AllStores {
		dir := filepath.Join(root, "database", store)
		if _, err := os.Stat(dir); err != nil {
			continue // store legitimately absent (lite snapshot pruning)
		}
		ldb, err := leveldb.OpenFile(dir, nil)
		if err != nil {
			t.Fatalf("equivalence: normalize-open %s in %s: %v", store, root, err)
		}
		if err := ldb.CompactRange(util.Range{}); err != nil {
			ldb.Close()
			t.Fatalf("equivalence: normalize-compact %s in %s: %v", store, root, err)
		}
		if err := ldb.Close(); err != nil {
			t.Fatalf("equivalence: normalize-close %s in %s: %v", store, root, err)
		}
	}
}

// javaHeapFlag returns the JVM `-Xmx<size>` flag for the equivalence
// invocation. Defaults to `-Xmx4g` which is enough for Nile lite
// snapshots; CI on smaller runners can override via DBFORK_JAVA_HEAP
// (e.g. `2g`, `512m`). Without an override, the JDK default (~256MB)
// OOMs the toolkit's store readers on a real fixture.
func javaHeapFlag() string {
	heap := os.Getenv("DBFORK_JAVA_HEAP")
	if heap == "" {
		heap = "4g"
	}
	return "-Xmx" + heap
}

// mustEnvFile returns (path, true) when an env var is set AND the
// pointed file/dir exists with the expected kind. SKIPs with a
// descriptive message otherwise. Centralizes the gating logic so
// each missing prereq produces a uniform "go test ./..." log line.
//
// expectDir distinguishes the Nile-fixture case (must be a directory
// — the test later does `filepath.Join(path, "database")`) from the
// JAR + conf cases (must be a regular file). Without the kind check,
// pointing DBFORK_NILE_FIXTURE at a file would surface a confusing
// copyDir error rather than a clear "expected directory" message.
func mustEnvFile(t *testing.T, envName, label string, expectDir bool) (string, bool) {
	t.Helper()
	p := os.Getenv(envName)
	if p == "" {
		t.Skipf("equivalence: %s ($%s) not set — see equivalence_test.go "+
			"docstring for setup. Skipping the Go-vs-Java release gate.",
			label, envName)
		return "", false
	}
	info, err := os.Stat(p)
	if err != nil {
		t.Skipf("equivalence: %s at %q ($%s) not accessible: %v — skipping.",
			label, p, envName, err)
		return "", false
	}
	if expectDir && !info.IsDir() {
		t.Skipf("equivalence: %s at %q ($%s) is a file, want a directory — skipping.",
			label, p, envName)
		return "", false
	}
	if !expectDir && info.IsDir() {
		t.Skipf("equivalence: %s at %q ($%s) is a directory, want a file — skipping.",
			label, p, envName)
		return "", false
	}
	return p, true
}

// diffStore opens the same store in both scratch dirs and compares
// every key-value pair. Splits raw vs proto-aware paths based on
// the store's content type.
func diffStore(t *testing.T, store, goRoot, javaRoot string) {
	t.Helper()
	goEng, err := db.OpenLevelDB(goRoot, store)
	if err != nil {
		t.Fatalf("open Go %s: %v", store, err)
	}
	defer goEng.Close()
	javaEng, err := db.OpenLevelDB(javaRoot, store)
	if err != nil {
		t.Fatalf("open Java %s: %v", store, err)
	}
	defer javaEng.Close()

	goMap, err := collectAllKV(goEng)
	if err != nil {
		t.Fatalf("collect Go %s: %v", store, err)
	}
	javaMap, err := collectAllKV(javaEng)
	if err != nil {
		t.Fatalf("collect Java %s: %v", store, err)
	}
	// Log per-store key counts so a vacuously-passing run (empty
	// store on both sides — possible if the lite snapshot pruned
	// `storage-row`, for example) is visible in the test log.
	t.Logf("%s: %d keys on Go, %d keys on Java", store, len(goMap), len(javaMap))

	// Key-set diff first — surfaces extra/missing keys before drowning
	// the log in value diffs.
	reportKeySetDiff(t, store, goMap, javaMap)

	// Per-key value compare. Cap reported diffs so a wholesale
	// regression doesn't write thousands of lines.
	const maxValueDiffs = 5
	diffs := 0
	keys := sortedHexKeys(goMap)
	for _, hk := range keys {
		jv, ok := javaMap[hk]
		if !ok {
			continue // already reported by reportKeySetDiff
		}
		gv := goMap[hk]
		if equal, why := compareValue(store, gv, jv); !equal {
			diffs++
			if diffs <= maxValueDiffs {
				t.Errorf("%s: key %s: %s", store, hk, why)
			}
		}
	}
	if diffs > maxValueDiffs {
		t.Errorf("%s: %d additional value diffs not shown (cap=%d)",
			store, diffs-maxValueDiffs, maxValueDiffs)
	}
}

// compareValue picks proto-aware or raw compare based on the store's
// schema. Returns (equal, why) where why is non-empty on mismatch.
func compareValue(store string, goVal, javaVal []byte) (bool, string) {
	switch store {
	case stores.WitnessStore:
		return compareProto(goVal, javaVal, &pb.Witness{})
	case stores.AccountStore:
		return compareProto(goVal, javaVal, &pb.Account{})
	case stores.ContractStore:
		return compareProto(goVal, javaVal, &pb.SmartContract{})
	case stores.AssetIssueV2Store:
		// DbFork doesn't write this store, so any diff is unexpected.
		// Proto-compare for robustness against future expansion.
		return compareProto(goVal, javaVal, &pb.AssetIssueContract{})
	default:
		// Raw byte stores: witness_schedule (concat addresses),
		// properties (BE int64), account-asset (BE int64),
		// storage-row (32-byte balance).
		if bytes.Equal(goVal, javaVal) {
			return true, ""
		}
		return false, fmt.Sprintf("raw bytes differ:\n go=%s\n java=%s",
			hex.EncodeToString(goVal), hex.EncodeToString(javaVal))
	}
}

// compareProto parses both sides into a fresh proto of the given type
// and compares with proto.Equal (which is field-aware and tolerant of
// proto3 map field encoding-order differences — the same divergence
// that motivates accounts.go's deterministic-marshal). Returns a
// human-readable diff via prototext on mismatch.
//
// proto.Equal is ORDER-DEPENDENT for repeated fields (Account.votes,
// Account.frozen, etc.). DbFork doesn't mutate these — both java and
// Go round-trip the on-disk order untouched — so the order-dependence
// is invisible at the equivalence boundary. If a future mutator
// rewrites a repeated field, this comment is the place to revisit.
func compareProto(goVal, javaVal []byte, exemplar proto.Message) (bool, string) {
	goCopy := proto.Clone(exemplar)
	if err := proto.Unmarshal(goVal, goCopy); err != nil {
		return false, fmt.Sprintf("Go-side unmarshal failed: %v", err)
	}
	javaCopy := proto.Clone(exemplar)
	if err := proto.Unmarshal(javaVal, javaCopy); err != nil {
		return false, fmt.Sprintf("Java-side unmarshal failed: %v", err)
	}
	if proto.Equal(goCopy, javaCopy) {
		return true, ""
	}
	// Use prototext for human-readable diffs (skips byte-level
	// noise that proto.Equal already proved equivalent).
	goText, _ := prototext.MarshalOptions{Multiline: true}.Marshal(goCopy)
	javaText, _ := prototext.MarshalOptions{Multiline: true}.Marshal(javaCopy)
	return false, fmt.Sprintf("proto fields differ:\n--- go ---\n%s\n--- java ---\n%s",
		string(goText), string(javaText))
}

// collectAllKV iterates the entire store into an in-memory map. For
// equivalence diffing this is fine — even a 100M-row store at 100
// bytes per row is 10GB; mainstream Nile lite fixtures are much
// smaller. If a future fixture is too large, swap to a streaming
// merge-join over sorted iterators.
func collectAllKV(eng db.Engine) (map[string][]byte, error) {
	out := map[string][]byte{}
	it := eng.NewIterator()
	defer it.Close()
	for it.Next() {
		k := it.Key()
		v := it.Value()
		out[hex.EncodeToString(k)] = v
	}
	if err := it.Error(); err != nil {
		return nil, err
	}
	return out, nil
}

// reportKeySetDiff reports keys present on one side but not the other.
// Caps reports so a wholesale regression doesn't flood the log.
func reportKeySetDiff(t *testing.T, store string, goMap, javaMap map[string][]byte) {
	t.Helper()
	const maxKeyDiffs = 5

	onlyGo := keysOnlyIn(goMap, javaMap)
	onlyJava := keysOnlyIn(javaMap, goMap)
	if len(onlyGo) > 0 {
		n := min(len(onlyGo), maxKeyDiffs)
		t.Errorf("%s: %d keys present only on Go side; first %d: %v",
			store, len(onlyGo), n, onlyGo[:n])
	}
	if len(onlyJava) > 0 {
		n := min(len(onlyJava), maxKeyDiffs)
		t.Errorf("%s: %d keys present only on Java side; first %d: %v",
			store, len(onlyJava), n, onlyJava[:n])
	}
}

func keysOnlyIn(a, b map[string][]byte) []string {
	var out []string
	for k := range a {
		if _, present := b[k]; !present {
			out = append(out, k)
		}
	}
	sort.Strings(out)
	return out
}

func sortedHexKeys(m map[string][]byte) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// copyDir recursively copies src into dst, creating dst if missing.
// Used to lay down two independent mutable scratch copies of the
// Nile fixture. Symlinks are followed; permissions preserved.
func copyDir(src, dst string) error {
	return filepath.WalkDir(src, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(src, path)
		target := filepath.Join(dst, rel)
		if d.IsDir() {
			info, err := d.Info()
			if err != nil {
				return err
			}
			return os.MkdirAll(target, info.Mode().Perm())
		}
		return copyFile(path, target)
	})
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	info, err := os.Stat(src)
	if err != nil {
		return err
	}
	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, info.Mode().Perm())
	if err != nil {
		return err
	}
	defer out.Close()
	if _, err := io.Copy(out, in); err != nil {
		return err
	}
	return nil
}

// --- Diff-helper unit tests ----------------------------------------------
//
// These exercise the per-store diff helpers without the Java toolkit
// or the Nile fixture, so the equivalence test's logic is itself
// pinned. A regression in compareValue/compareProto/keysOnlyIn would
// surface here even when the full release gate doesn't run.

func TestCompareValue_RawByteEqual(t *testing.T) {
	a := []byte{1, 2, 3}
	b := []byte{1, 2, 3}
	equal, why := compareValue(stores.DynamicPropertiesStore, a, b)
	if !equal {
		t.Errorf("expected equal, got why=%q", why)
	}
}

func TestCompareValue_RawByteDiffers(t *testing.T) {
	a := []byte{1, 2, 3}
	b := []byte{1, 2, 4}
	equal, why := compareValue(stores.StorageRowStore, a, b)
	if equal {
		t.Error("expected diff, got equal")
	}
	for _, want := range []string{"raw bytes differ", "010203", "010204"} {
		if !strings.Contains(why, want) {
			t.Errorf("diff message missing %q: %s", want, why)
		}
	}
}

// TestCompareValue_ProtoMapEqualUnderReordering pins the proto.Equal-
// based map handling. Two Account protos with the same AssetV2 entries
// in different insertion orders MUST compare equal — otherwise Java's
// non-deterministic marshalling vs Go's deterministic marshalling
// would falsely fail the equivalence gate.
//
// Construction note: we hand-build two wire-format byte sequences with
// the AssetV2 entries in EXPLICITLY reversed order, instead of relying
// on Go's map iteration ordering. Map iteration is randomized at
// runtime but the randomization seed is stable within a process, so a
// `proto.Marshal` of two map literals with the same entries can
// accidentally produce identical bytes — which would make this test
// pass even if compareValue did byte-equality. The hand-built bytes
// guarantee the precondition we care about (goBytes != javaBytes) and
// the test asserts it explicitly.
func TestCompareValue_ProtoMapEqualUnderReordering(t *testing.T) {
	addr := bytes.Repeat([]byte{0x41}, 21)

	// Build the wire format by composing each side from two
	// single-entry Accounts. proto3 map fields are encoded as a
	// repeated entry; two consecutive entries can appear in either
	// order on the wire and decode to the same map.
	mk := func(id string, bal int64) []byte {
		raw, _ := proto.Marshal(&pb.Account{
			Address: addr,
			AssetV2: map[string]int64{id: bal},
		})
		return raw
	}
	entryA := mk("1000001", 100)
	entryB := mk("1000002", 200)

	// Strip the address from entryB's bytes and append to entryA;
	// the proto3 wire format allows duplicate field encoding (later
	// values append for map/repeated). The result decodes to a
	// 2-entry map but the on-wire order differs by argument order.
	goBytes := append([]byte{}, entryA...)
	goBytes = append(goBytes, entryB...)
	javaBytes := append([]byte{}, entryB...)
	javaBytes = append(javaBytes, entryA...)

	if bytes.Equal(goBytes, javaBytes) {
		t.Fatal("test precondition: hand-built byte sequences must differ; " +
			"the proto.Equal robustness is not actually being exercised")
	}

	equal, why := compareValue(stores.AccountStore, goBytes, javaBytes)
	if !equal {
		t.Errorf("proto.Equal-based diff failed under map reordering: %s", why)
	}
}

func TestCompareValue_ProtoDifferentFieldFails(t *testing.T) {
	goWitness := &pb.Witness{
		Address:   bytes.Repeat([]byte{0x41}, 21),
		VoteCount: 100,
	}
	javaWitness := &pb.Witness{
		Address:   bytes.Repeat([]byte{0x41}, 21),
		VoteCount: 101, // deliberate diff
	}
	goBytes, _ := proto.Marshal(goWitness)
	javaBytes, _ := proto.Marshal(javaWitness)
	equal, why := compareValue(stores.WitnessStore, goBytes, javaBytes)
	if equal {
		t.Error("expected proto diff on different VoteCount")
	}
	if !strings.Contains(why, "proto fields differ") {
		t.Errorf("diff message should mention proto fields: %s", why)
	}
	// prototext uses the proto3 camelCase JSON name `voteCount`, not
	// the wire-format name `vote_count`. Both 100 and 101 should
	// appear in the diff so an operator can see the discrepancy.
	if !strings.Contains(why, "voteCount") {
		t.Errorf("diff message should mention voteCount, got: %s", why)
	}
	if !strings.Contains(why, "100") || !strings.Contains(why, "101") {
		t.Errorf("diff message should show both values, got: %s", why)
	}
}

func TestKeysOnlyIn_ReturnsDifference(t *testing.T) {
	a := map[string][]byte{"k1": nil, "k2": nil, "k3": nil}
	b := map[string][]byte{"k2": nil}
	got := keysOnlyIn(a, b)
	want := []string{"k1", "k3"}
	if len(got) != len(want) {
		t.Fatalf("keysOnlyIn = %v; want %v", got, want)
	}
	for i, k := range want {
		if got[i] != k {
			t.Errorf("keysOnlyIn[%d] = %q; want %q", i, got[i], k)
		}
	}
}

// TestCopyDir_RoundTrip is a tiny round-trip: write a few files into
// tmpA, copy to tmpB, verify identical contents. Catches a regression
// in the filepath.WalkDir loop without needing the multi-GB Nile
// fixture.
func TestCopyDir_RoundTrip(t *testing.T) {
	src := t.TempDir()
	dst := filepath.Join(t.TempDir(), "copy")
	files := map[string][]byte{
		"a.txt":          []byte("alpha"),
		"sub/b.txt":      []byte("bravo"),
		"sub/deep/c.txt": []byte("charlie"),
	}
	for name, content := range files {
		full := filepath.Join(src, name)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, content, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	if err := copyDir(src, dst); err != nil {
		t.Fatalf("copyDir: %v", err)
	}
	for name, want := range files {
		got, err := os.ReadFile(filepath.Join(dst, name))
		if err != nil {
			t.Errorf("read %s: %v", name, err)
			continue
		}
		if !bytes.Equal(got, want) {
			t.Errorf("%s: got %q, want %q", name, got, want)
		}
	}
}

// Note: the "skip cleanly when env vars missing" path is exercised
// by every `go test ./...` run on a machine without the Java toolkit
// or Nile fixture — TestEquivalence_GoVsJava itself reports SKIP
// under those conditions, which is visible in `go test -v` output
// and would surface as a test FAILURE (not skip) if a regression
// broke the gating. A separate "test the skip" test is unnecessary.
